// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.2.1

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type PassportHTTPServer interface {
	GetPassport(context.Context, *GetPassportRequest) (*GetPassportReply, error)
}

func RegisterPassportHTTPServer(s *http.Server, srv PassportHTTPServer) {
	r := s.Route("/")
	r.GET("/passport", _Passport_GetPassport0_HTTP_Handler(srv))
}

func _Passport_GetPassport0_HTTP_Handler(srv PassportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPassportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/passport.v1.Passport/GetPassport")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPassport(ctx, req.(*GetPassportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPassportReply)
		return ctx.Result(200, reply)
	}
}

type PassportHTTPClient interface {
	GetPassport(ctx context.Context, req *GetPassportRequest, opts ...http.CallOption) (rsp *GetPassportReply, err error)
}

type PassportHTTPClientImpl struct {
	cc *http.Client
}

func NewPassportHTTPClient(client *http.Client) PassportHTTPClient {
	return &PassportHTTPClientImpl{client}
}

func (c *PassportHTTPClientImpl) GetPassport(ctx context.Context, in *GetPassportRequest, opts ...http.CallOption) (*GetPassportReply, error) {
	var out GetPassportReply
	pattern := "/passport"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/passport.v1.Passport/GetPassport"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
