// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: api/passport/v1/passport.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreatePassportRequest
type CreatePassportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePassportRequest) Reset() {
	*x = CreatePassportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_passport_v1_passport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePassportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePassportRequest) ProtoMessage() {}

func (x *CreatePassportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePassportRequest.ProtoReflect.Descriptor instead.
func (*CreatePassportRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{0}
}

// CreatePassportReply
type CreatePassportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePassportReply) Reset() {
	*x = CreatePassportReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_passport_v1_passport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePassportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePassportReply) ProtoMessage() {}

func (x *CreatePassportReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePassportReply.ProtoReflect.Descriptor instead.
func (*CreatePassportReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{1}
}

// DeletePassportRequest
type DeletePassportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePassportRequest) Reset() {
	*x = DeletePassportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_passport_v1_passport_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePassportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePassportRequest) ProtoMessage() {}

func (x *DeletePassportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePassportRequest.ProtoReflect.Descriptor instead.
func (*DeletePassportRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{2}
}

// DeletePassportReply
type DeletePassportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePassportReply) Reset() {
	*x = DeletePassportReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_passport_v1_passport_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePassportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePassportReply) ProtoMessage() {}

func (x *DeletePassportReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePassportReply.ProtoReflect.Descriptor instead.
func (*DeletePassportReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{3}
}

// GetPassportRequest
type GetPassportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPassportRequest) Reset() {
	*x = GetPassportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_passport_v1_passport_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPassportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassportRequest) ProtoMessage() {}

func (x *GetPassportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassportRequest.ProtoReflect.Descriptor instead.
func (*GetPassportRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{4}
}

func (x *GetPassportRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetPassportReply
type GetPassportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPassportReply) Reset() {
	*x = GetPassportReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_passport_v1_passport_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPassportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassportReply) ProtoMessage() {}

func (x *GetPassportReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassportReply.ProtoReflect.Descriptor instead.
func (*GetPassportReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{5}
}

// UpdatePassportRequest
type UpdatePassportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePassportRequest) Reset() {
	*x = UpdatePassportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_passport_v1_passport_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePassportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePassportRequest) ProtoMessage() {}

func (x *UpdatePassportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePassportRequest.ProtoReflect.Descriptor instead.
func (*UpdatePassportRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{6}
}

// UpdatePassportReply
type UpdatePassportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePassportReply) Reset() {
	*x = UpdatePassportReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_passport_v1_passport_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePassportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePassportReply) ProtoMessage() {}

func (x *UpdatePassportReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePassportReply.ProtoReflect.Descriptor instead.
func (*UpdatePassportReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{7}
}

// ListPassportRequest
type ListPassportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPassportRequest) Reset() {
	*x = ListPassportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_passport_v1_passport_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPassportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPassportRequest) ProtoMessage() {}

func (x *ListPassportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPassportRequest.ProtoReflect.Descriptor instead.
func (*ListPassportRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{8}
}

// ListPassportReply
type ListPassportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPassportReply) Reset() {
	*x = ListPassportReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_passport_v1_passport_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPassportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPassportReply) ProtoMessage() {}

func (x *ListPassportReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPassportReply.ProtoReflect.Descriptor instead.
func (*ListPassportReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{9}
}

var File_api_passport_v1_passport_proto protoreflect.FileDescriptor

var file_api_passport_v1_passport_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x2d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x15, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13,
	0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x32, 0xce, 0x03, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x58, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x22, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x22, 0x2e, 0x70,
	0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x1f, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x12, 0x09, 0x2f, 0x70, 0x61,
	0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x58, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x22, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70,
	0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x52, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x20, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x4b, 0x0a, 0x1a, 0x64, 0x65, 0x76, 0x2e, 0x6b, 0x72, 0x61, 0x74,
	0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x76, 0x31, 0x42, 0x0f, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_passport_v1_passport_proto_rawDescOnce sync.Once
	file_api_passport_v1_passport_proto_rawDescData = file_api_passport_v1_passport_proto_rawDesc
)

func file_api_passport_v1_passport_proto_rawDescGZIP() []byte {
	file_api_passport_v1_passport_proto_rawDescOnce.Do(func() {
		file_api_passport_v1_passport_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_passport_v1_passport_proto_rawDescData)
	})
	return file_api_passport_v1_passport_proto_rawDescData
}

var file_api_passport_v1_passport_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_passport_v1_passport_proto_goTypes = []interface{}{
	(*CreatePassportRequest)(nil), // 0: passport.v1.CreatePassportRequest
	(*CreatePassportReply)(nil),   // 1: passport.v1.CreatePassportReply
	(*DeletePassportRequest)(nil), // 2: passport.v1.DeletePassportRequest
	(*DeletePassportReply)(nil),   // 3: passport.v1.DeletePassportReply
	(*GetPassportRequest)(nil),    // 4: passport.v1.GetPassportRequest
	(*GetPassportReply)(nil),      // 5: passport.v1.GetPassportReply
	(*UpdatePassportRequest)(nil), // 6: passport.v1.UpdatePassportRequest
	(*UpdatePassportReply)(nil),   // 7: passport.v1.UpdatePassportReply
	(*ListPassportRequest)(nil),   // 8: passport.v1.ListPassportRequest
	(*ListPassportReply)(nil),     // 9: passport.v1.ListPassportReply
}
var file_api_passport_v1_passport_proto_depIdxs = []int32{
	0, // 0: passport.v1.Passport.CreatePassport:input_type -> passport.v1.CreatePassportRequest
	2, // 1: passport.v1.Passport.DeletePassport:input_type -> passport.v1.DeletePassportRequest
	4, // 2: passport.v1.Passport.GetPassport:input_type -> passport.v1.GetPassportRequest
	6, // 3: passport.v1.Passport.UpdatePassport:input_type -> passport.v1.UpdatePassportRequest
	8, // 4: passport.v1.Passport.ListPassport:input_type -> passport.v1.ListPassportRequest
	1, // 5: passport.v1.Passport.CreatePassport:output_type -> passport.v1.CreatePassportReply
	3, // 6: passport.v1.Passport.DeletePassport:output_type -> passport.v1.DeletePassportReply
	5, // 7: passport.v1.Passport.GetPassport:output_type -> passport.v1.GetPassportReply
	7, // 8: passport.v1.Passport.UpdatePassport:output_type -> passport.v1.UpdatePassportReply
	9, // 9: passport.v1.Passport.ListPassport:output_type -> passport.v1.ListPassportReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_passport_v1_passport_proto_init() }
func file_api_passport_v1_passport_proto_init() {
	if File_api_passport_v1_passport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_passport_v1_passport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePassportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_passport_v1_passport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePassportReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_passport_v1_passport_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePassportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_passport_v1_passport_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePassportReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_passport_v1_passport_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPassportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_passport_v1_passport_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPassportReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_passport_v1_passport_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePassportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_passport_v1_passport_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePassportReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_passport_v1_passport_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPassportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_passport_v1_passport_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPassportReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_passport_v1_passport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_passport_v1_passport_proto_goTypes,
		DependencyIndexes: file_api_passport_v1_passport_proto_depIdxs,
		MessageInfos:      file_api_passport_v1_passport_proto_msgTypes,
	}.Build()
	File_api_passport_v1_passport_proto = out.File
	file_api_passport_v1_passport_proto_rawDesc = nil
	file_api_passport_v1_passport_proto_goTypes = nil
	file_api_passport_v1_passport_proto_depIdxs = nil
}
