// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	"service/app/passport/internal/biz"
	"service/app/passport/internal/data"
	"service/app/passport/internal/server"
	"service/app/passport/internal/service"
	"service/pkg/conf"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confService *conf.Service, registrar registry.Registrar, discovery registry.Discovery, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(logger)
	if err != nil {
		return nil, nil, err
	}
	passportRepo := data.NewPassportRepo(dataData, logger)
	passportUseCase := biz.NewPassportUseCase(passportRepo, logger)
	passportService := service.NewPassportService(passportUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, passportService, logger)
	grpcServer := server.NewGRPCServer(confServer, passportService, logger)
	app := newApp(logger, registrar, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
