server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:6002
    timeout: 1s

service:
  data:
    database:
      driver: mysql
      source: root:123456@tcp(127.0.0.1:3306)/touhou_gamejam?charset=utf8mb4&parseTime=True&loc=Local
      max_idle_conn: 50
      max_open_conn: 100
      conn_max_lifetime: 30s
    redis:
      network: tcp
      addr: 127.0.0.1:6379
      password: ""
      read_timeout: 0.2s
      write_timeout: 0.2s
    objectStorage:
      domain: localhost:9000
      access_key_id: minioadmin
      secret_access_key: minioadmin
      location: cn-north-1
      secure: false
      token: ""
email:
  user: mail@mailpush.thjam.cc
  pass: iTvLd6f9cKwQ3yn
  host: smtpdm.aliyun.com
  port: 80

user:
  default_user_avatar_hash: aaa
  user_avatar_bucket_name:  useravatarbucket
